In [2]:
import numpy


In [3]:
inarray = numpy.loadtxt(fname='inflammation/data/inflammation-01.csv', delimiter=',')
print inarray.shape

(60L, 40L)


In [4]:
#create an empty array
a = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print a
print "our whole array is\n", a.shape
print a[0,:]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
our whole array is
(3L, 4L)
[1 2 3 4]


In [5]:
a[1,]
a[1,:2]
# note that if you want the first 2 columns of row 2, you gotta put 2 for column not 1, cos if you put 1 it will go up to but not include index 1


array([5, 6])

In [6]:
sum (a[:,2])


21

In [7]:
sum (a[,2])


SyntaxError: invalid syntax (<ipython-input-7-13b11082fdbe>, line 1)

In [ ]:
print data.mean(axis=0)